version: '2'
services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./code:/code
      - ./site.conf:/etc/nginx/conf.d/site.conf
    links:
      - php
  php:
    build: ./docker/php7
    ports:
      - "9000"
    volumes:
      - ./code:/code
    working_dir: /code
    environment:
      XDEBUG_CONFIG: remote_host=192.168.50.71 #Подставить свой удаленный IP
      PHP_IDE_CONFIG: "serverName=server"
  db:
    container_name: db
    build: ./docker/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./docker/mysql/mysql-data:/var/lib/mysql
      - ./docker/mysql/dumps:/docker-entrypoint-initdb.d
